apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backend
  namespace: argocd
spec:
  description: Backend API application
  sourceRepos:
    - 'git@github.com:CHARANPRAJWAL/gitops-deploy.git'   # Replace <GITHUB_ORG>
  destinations:
    - namespace: backend-production
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: external-secrets.io
      kind: ExternalSecret
    - group: ''
      kind: Secret
    - group: batch
      kind: Job
