apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-degraded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: backend
  source:
    repoURL: 'git@github.com:<GITHUB_ORG>/gitops-deploy.git'   # Replace <GITHUB_ORG>
    targetRevision: main
    path: charts/backend
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
